#!/usr/bin/env python3
"""Census the vector instructions in the shipped WebAssembly module.

Every "SIMD made this faster" demo on the web asks to be taken on trust twice:
that the fast path really is vectorised, and that the baseline really is not.
This project's answer has been a source comment saying the reference is
"intentionally NOT optimized to provide a fair comparison" — which is true, and
is still just a claim.

The artifact that settles it is already in the visitor's cache: the `.wasm`
module the page just executed. This script disassembles it and records what is
actually in there.

    python3 tools/wasm_census.py --write    # needs wabt (brew install wabt)
    python3 tools/wasm_census.py --check    # stdlib only, runs in CI

`--write` needs `wasm-objdump`. `--check` does not: the census records the
sha256 of the module it was taken from, so CI only has to prove the committed
census still describes the committed binary. That keeps the expensive tool off
the runner while making a stale census impossible.

Note what this can and cannot say. Emscripten strips the name section at -O3, so
the module carries no source-level function names — the census reports function
*indices*, never "this is dot_wasm128_rowvec". What it can show is the shape:
the count of `v128.load → f64x2.mul → f64x2.add` triples is the signature of the
dual-accumulator dot product in src/NeuralNet.cpp, unrolled by the compiler.
Claiming more than that from a stripped binary would be the kind of overclaim
this file exists to prevent.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MODULE = ROOT / "web/public/wasm/fast_mnist.wasm"
OUT = ROOT / "docs/benchmarks/wasm-simd-census.json"

# Any instruction whose mnemonic starts with one of these is a 128-bit vector
# instruction (the 0xFD opcode prefix in the binary format).
VECTOR = re.compile(r"^(v128|i8x16|i16x8|i32x4|i64x2|f32x4|f64x2)\.")

# The inner loop of a dual-accumulator dot product: load a vector of weights,
# multiply by a vector of inputs, accumulate. Two independent chains of this are
# what keep the FMA pipeline from serialising on itself.
SIGNATURE = ("v128.load", "f64x2.mul", "f64x2.add")

FUNC_HEADER = re.compile(r"^[0-9a-f]{6} func\[(\d+)\](?: <(.+?)>)?:")
INSTRUCTION = re.compile(r"^\s*[0-9a-f]{6}: [0-9a-f ]+\|\s+(\S+)")


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def disassemble() -> str:
    tool = shutil.which("wasm-objdump")
    if not tool:
        raise SystemExit(
            "wasm-objdump not found. Install wabt (`brew install wabt`, or "
            "`apt-get install wabt`). Only --write needs it; --check does not."
        )
    result = subprocess.run([tool, "-d", str(MODULE)], capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"wasm-objdump failed:\n{result.stderr}")
    return result.stdout


def build() -> dict:
    text = disassemble()
    current: int | None = None
    bodies: dict[int, list[str]] = collections.defaultdict(list)
    names: dict[int, str] = {}

    for line in text.splitlines():
        header = FUNC_HEADER.match(line)
        if header:
            current = int(header.group(1))
            if header.group(2):
                names[current] = header.group(2)
            continue
        insn = INSTRUCTION.match(line)
        if insn and current is not None:
            bodies[current].append(insn.group(1))

    if not bodies:
        raise SystemExit("parsed zero functions — the wasm-objdump output format has changed")

    opcodes: collections.Counter[str] = collections.Counter()
    vector_funcs = []
    signature_hits = 0

    for index, body in sorted(bodies.items()):
        vec = [op for op in body if VECTOR.match(op)]
        if not vec:
            continue
        opcodes.update(vec)
        hits = sum(
            1
            for i in range(len(body) - len(SIGNATURE) + 1)
            if tuple(body[i : i + len(SIGNATURE)]) == SIGNATURE
        )
        signature_hits += hits
        vector_funcs.append(
            {
                "index": index,
                "name": names.get(index),
                "instructions": len(body),
                "vectorInstructions": len(vec),
                "signatureHits": hits,
            }
        )

    return {
        "$comment": (
            "Generated by tools/wasm_census.py from the committed "
            "web/public/wasm/fast_mnist.wasm. Regenerate with --write (needs wabt); "
            "CI runs --check, which only verifies moduleSha256 still matches."
        ),
        "module": "web/public/wasm/fast_mnist.wasm",
        "moduleSha256": sha256(MODULE),
        "moduleBytes": MODULE.stat().st_size,
        "totalFunctions": len(bodies),
        "functionsWithVectorInstructions": len(vector_funcs),
        "totalVectorInstructions": sum(opcodes.values()),
        "signature": list(SIGNATURE),
        "signatureHits": signature_hits,
        "opcodes": dict(opcodes.most_common()),
        "functions": vector_funcs,
        "namesStripped": len(names) < len(bodies),
    }


def check() -> int:
    if not OUT.exists():
        print(f"MISSING {OUT.relative_to(ROOT)} — run tools/wasm_census.py --write", file=sys.stderr)
        return 1
    census = json.loads(OUT.read_text())
    actual = sha256(MODULE)
    if census.get("moduleSha256") != actual:
        print(
            f"STALE {OUT.relative_to(ROOT)}: it was taken from a module with sha256\n"
            f"  {census.get('moduleSha256')}\n"
            f"but web/public/wasm/fast_mnist.wasm is now\n  {actual}\n"
            f"Re-run `python3 tools/wasm_census.py --write` (needs wabt) and commit it.",
            file=sys.stderr,
        )
        return 1
    if census.get("moduleBytes") != MODULE.stat().st_size:
        print(f"STALE {OUT.relative_to(ROOT)}: recorded byte length disagrees", file=sys.stderr)
        return 1

    # The digest above proves the census was taken from THIS module. It does
    # not prove the census still says what the disassembly said, and the three
    # headline numbers below are rendered on the landing page. Until
    # tools/check_gates.py mutated `totalVectorInstructions` from 154 to 155
    # and watched this exit 0, nothing here read them at all: a hand-edited
    # count would have shipped to the page with every gate green, which is the
    # precise defect shape --check exists to prevent.
    #
    # Re-deriving them needs wabt, which --check deliberately does not require.
    # Internal consistency does not: the histogram and the function list are
    # the evidence, the totals are summaries of them, and a summary that
    # disagrees with its own evidence is wrong no matter which one drifted.
    summaries = []
    opcodes = census.get("opcodes")
    if isinstance(opcodes, dict):
        summaries.append(("totalVectorInstructions", sum(opcodes.values()), "sum of `opcodes`"))
    functions = census.get("functions")
    if isinstance(functions, list):
        summaries.append(
            ("functionsWithVectorInstructions", len(functions), "length of `functions`")
        )
    if not summaries:
        print(
            f"{OUT.relative_to(ROOT)}: neither `opcodes` nor `functions` is present, so the "
            f"published totals cannot be cross-checked. The schema changed and this gate has "
            f"gone blind — fix it rather than deleting this message.",
            file=sys.stderr,
        )
        return 1
    for key, derived, source in summaries:
        if census.get(key) != derived:
            print(
                f"INCONSISTENT {OUT.relative_to(ROOT)}: `{key}` says {census.get(key)} but the "
                f"{source} is {derived}. The module's digest still matches, so the census was "
                f"edited by hand rather than regenerated. Re-run --write (needs wabt).",
                file=sys.stderr,
            )
            return 1

    print(
        f"OK {OUT.relative_to(ROOT)} describes the committed module — "
        f"{census['totalVectorInstructions']} vector instructions in "
        f"{census['functionsWithVectorInstructions']} of {census['totalFunctions']} functions"
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if args.check:
        return check()

    census = build()
    OUT.write_text(json.dumps(census, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {census['totalFunctions']} functions, "
          f"{census['functionsWithVectorInstructions']} contain vector instructions")
    print(f"  {census['totalVectorInstructions']} vector instructions total")
    print(f"  {census['signatureHits']} × {' -> '.join(SIGNATURE)} (dual-accumulator inner loop)")
    print(f"  names stripped: {census['namesStripped']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
