name: commitlint

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-commits:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Lint commits with commitlint
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed
        with:
          configFile: web/commitlint.config.mjs
