name: Fuzzing

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: fuzzing-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clusterfuzzlite:
    name: ClusterFuzzLite / address
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1
        with:
          language: c++
          sanitizer: address
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1
        with:
          mode: code-change
          sanitizer: address
          fuzz-seconds: 120
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-sarif: false
